# Generated by Django 2.1.1 on 2018-09-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bell',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
