# Generated by Django 2.1.1 on 2018-09-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0002_bell_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bell',
            old_name='payload',
            new_name='context',
        ),
    ]
