# Generated by Django 2.1.1 on 2018-09-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickups', '0002_remove_pickupdate_notifications_sent'),
    ]

    operations = [
        # add explicit through model for pickup date collectors
        # nothing in the database should change, we only need to make sure that Django accepts the state change
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PickupDateCollector',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                    ],
                    options={
                        'db_table': 'pickups_pickupdate_collectors',
                    },
                ),
                migrations.AlterField(
                    model_name='pickupdate',
                    name='collectors',
                    field=models.ManyToManyField(
                        related_name='pickup_dates',
                        through='pickups.PickupDateCollector',
                        to=settings.AUTH_USER_MODEL
                    ),
                ),
                migrations.AddField(
                    model_name='pickupdatecollector',
                    name='pickupdate',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickups.PickupDate'),
                ),
                migrations.AddField(
                    model_name='pickupdatecollector',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterUniqueTogether(
                    name='pickupdatecollector',
                    unique_together={('pickupdate', 'user')},
                ),
            ],
        ),
    ]
