# Generated by Django 2.1.1 on 2018-09-20 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0003_auto_20180920_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdatecollector',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
