# Generated by Django 2.1.5 on 2019-01-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0007_auto_20181216_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupdatecollector',
            options={'ordering': ['-created_at']},
        ),
    ]
