# Generated by Django 2.2 on 2019-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0015_auto_20190129_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdate',
            name='type',
            field=models.CharField(choices=[('pickup', 'pickup'), ('meeting', 'meeting')], default='pickup', max_length=255),
        ),
    ]
