# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date']},
        ),
    ]
