# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:31
from __future__ import unicode_literals

from django.db import migrations, connection

def rename_tables(apps, schema_editor):
    cursor = connection.cursor()

    cursor.execute("SELECT to_regclass('public.history_history_users')")
    row = cursor.fetchone()
    if row[0] == "history_history_users":
        cursor.execute("DROP TABLE activity_activity_users")
        cursor.execute("ALTER TABLE history_history_users RENAME TO activity_activity_users")
        cursor.execute("ALTER TABLE activity_activity_users RENAME history_id TO activity_id")

    cursor.execute("SELECT to_regclass('public.history_history')")
    row = cursor.fetchone()
    if row[0] == "history_history":
        cursor.execute("DROP TABLE activity_activity")
        cursor.execute("ALTER TABLE history_history RENAME TO activity_activity")

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20170701_1555'),
    ]

    operations = [
        migrations.RenameModel('History', 'Activity'),
        migrations.RunPython(rename_tables)
    ]
