# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-08-01 13:49
=======
# Generated by Django 1.11.3 on 2017-08-01 14:32
>>>>>>> e9b72fa4785fa41179077545f8eb2bfd7977021e
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0015_auto_20170727_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
<<<<<<< HEAD
                ('weight', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=80)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.PickupDate')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
=======
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('comment', models.TextField(max_length=500)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.PickupDate')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> e9b72fa4785fa41179077545f8eb2bfd7977021e
            ],
            options={
                'abstract': False,
            },
        ),
    ]
