# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0015_auto_20170727_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=80)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.PickupDate')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([('weight', 'comment')]),
        ),
    ]
