# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([('weight', 'comment')]),
        ),
    ]
