# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20170809_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='about',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='given_by',
        ),
    ]
