# Generated by Django 2.1.2 on 2018-11-23 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0030_store_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='last_changed_message',
            field=models.TextField(null=True),
        ),
    ]
