# Generated by Django 2.1.2 on 2018-12-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_store_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='created_by',
            new_name='last_changed_by',
        ),
    ]
