# Generated by Django 2.1.2 on 2018-12-09 15:55

from django.db import migrations


def remove_deleted_stores(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Store.objects.filter(deleted=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_auto_20181207_2210'),
    ]

    operations = [
        migrations.RunPython(remove_deleted_stores, migrations.RunPython.noop, elidable=True),
    ]
