# Generated by Django 2.1.2 on 2018-12-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_auto_20181207_2210'),
    ]

    operations = [
        # TODO add data migration to mark deleted stores as archived
        migrations.RemoveField(
            model_name='store',
            name='deleted',
        ),
    ]
