# Generated by Django 2.1.2 on 2018-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_auto_20181123_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='last_changed_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
