# Generated by Django 2.1.5 on 2019-01-24 20:13
from django.db import migrations


def add_store_participants(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Conversation = apps.get_model('conversations', 'Conversation')
    ConversationParticipant = apps.get_model('conversations', 'ConversationParticipant')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.get(app_label='stores', model='store')

    for store in Store.objects.all():
        conversation, _ = Conversation.objects.get_or_create(target_type=ct, target_id=store.id)
        for user in store.group.members.all():
            ConversationParticipant.objects.create(user=user, conversation=conversation)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_auto_20181216_2133'),
        ('conversations', '0026_conversationmeta'),
        ('groups', '0036_group_photo'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [migrations.RunPython(add_store_participants, migrations.RunPython.noop, elidable=True)]
