# Generated by Django 2.1.2 on 2018-11-28 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_auto_20181124_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='store',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
