# Generated by Django 2.1.5 on 2019-01-30 11:28
from dateutil.relativedelta import relativedelta
from django.contrib.auth import get_user_model
from django.db import migrations
from django.utils import timezone


def add_store_subscriptions(apps, schema_editor):
    """Adds store subscribers
    Only adds users who signed up for pickups one week ago or later
    """
    Store = apps.get_model('stores', 'Store')
    StoreSubscription = apps.get_model('stores', 'StoreSubscription')
    Conversation = apps.get_model('conversations', 'Conversation')
    ConversationParticipant = apps.get_model('conversations', 'ConversationParticipant')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.get(app_label='stores', model='store')

    for store in Store.objects.all():
        conversation, _ = Conversation.objects.get_or_create(target_type=ct, target_id=store.id)
        one_week_ago = timezone.now() - relativedelta(days=7)
        recent_collectors = get_user_model().objects.filter(
            pickup_dates__date__startswith__gte=one_week_ago,
            pickup_dates__store_id=store.id,
        ).distinct()
        for user in recent_collectors:
            StoreSubscription.objects.create(user=user, store=store)
            ConversationParticipant.objects.create(user=user, conversation=conversation)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_auto_20190130_1128'),
        ('pickups', '0013_auto_20190122_1210'),
        ('conversations', '0026_conversationmeta'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [migrations.RunPython(add_store_subscriptions, migrations.RunPython.noop, elidable=True)]
