# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160810_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImage',
            new_name='ProfilePicture',
        ),
    ]
