# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161230_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': []},
        ),
    ]
