# Generated by Django 2.0.1 on 2018-02-27 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_auto_20171207_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
