# Generated by Django 2.0.1 on 2018-02-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_groupmembership_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='last_seen',
            new_name='lastseen_at',
        ),
    ]
