# Generated by Django 2.0.2 on 2018-03-02 12:11

import django.contrib.postgres.fields
from django.db import migrations, models
import foodsaving.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_groupmembership_lastseen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=foodsaving.groups.models.get_default_notifications, size=None),
        ),
    ]
