# Generated by Django 2.0.2 on 2018-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
