# Generated by Django 2.0.2 on 2018-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_groupmembership_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='inactive_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
