# Generated by Django 2.0.2 on 2018-03-04 19:22

from django.db import migrations

from foodsaving.groups.roles import GROUP_APPROVED_MEMBER


def grant_approved_role_to_members(apps, schema_editor):
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for o in GroupMembership.objects.all():
        if GROUP_APPROVED_MEMBER not in o.roles:
            o.roles.append(GROUP_APPROVED_MEMBER)
            o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_add_group_names_view_20180310_1034'),
    ]

    operations = [
        migrations.RunPython(grant_approved_role_to_members, migrations.RunPython.noop)
    ]
