# Generated by Django 2.0.7 on 2018-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20180713_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined'), ('withdrawn', 'withdrawn')], default='pending', max_length=100),
        ),
    ]
