# Generated by Django 2.0.7 on 2018-07-10 20:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0030_auto_20180710_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupapplication',
            unique_together={('user', 'group')},
        ),
    ]
