# Generated by Django 2.0.7 on 2018-07-13 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0031_groupapplication_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupapplication',
            unique_together={('user', 'group', 'status')},
        ),
    ]
