# Generated by Django 2.0.7 on 2018-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_auto_20180710_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='application_questions',
            field=models.TextField(blank=True),
        ),
    ]
