# Generated by Django 2.0.7 on 2018-07-22 22:51

from django.db import migrations


def make_all_full_members(apps, schema_editor):
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for membership in GroupMembership.objects.all():
        if 'full_member' not in membership.roles:
            membership.roles.append('full_member')
            membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_add_default_notification_20180715_1040'),
    ]

    operations = [
        migrations.RunPython(make_all_full_members, migrations.RunPython.noop)
    ]
