# Generated by Django 2.0.7 on 2018-08-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0031_add_default_notification_20180715_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupmembership_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
