# Generated by Django 2.0.7 on 2018-07-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_auto_20180713_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='applications',
        ),
        migrations.AlterUniqueTogether(
            name='groupapplication',
            unique_together=set(),
        ),
    ]
