# Generated by Django 2.0.7 on 2018-07-30 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0032_auto_20180722_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_given', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust', to='groups.GroupMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
