# Generated by Django 2.0.7 on 2018-08-05 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0032_make_all_members_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_given', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMembership')),
            ],
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='trusted_by',
            field=models.ManyToManyField(related_name='membership', through='groups.Trust', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trust',
            unique_together={('membership', 'given_by')},
        ),
    ]
