# Generated by Django 2.0.7 on 2018-07-30 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0033_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='trust',
            field=models.ManyToManyField(related_name='membership', through='groups.Trust', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trust',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='groups.GroupMembership'),
        ),
    ]
