# Generated by Django 2.0.7 on 2018-07-14 10:42
from enum import Enum

from django.db import migrations, models


class GroupStatus(Enum):
    ACTIVE = 'active'
    INACTIVE = 'inactive'
    PLAYGROUND = 'playground'


def migrate_playground_groups_to_be_open(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    Group.objects.filter(status=GroupStatus.PLAYGROUND.value).update(is_open=True)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20180713_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_playground_groups_to_be_open, reverse_code=migrations.RunPython.noop),
    ]
