# Generated by Django 2.0.7 on 2018-07-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20180730_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='trust',
            new_name='trusted_by',
        ),
        migrations.AlterField(
            model_name='trust',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMembership'),
        ),
    ]
