# Generated by Django 2.0.7 on 2018-07-31 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0035_auto_20180730_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trust',
            unique_together={('membership', 'given_by')},
        ),
    ]
