services:
  - name: "database"
    image: "postgres:14-alpine"
    # Test performance: don't flush every write to disk
    command: "-c fsync=off"
    environment:
      - POSTGRES_USER=karrot
      - POSTGRES_DB=karrot
      - POSTGRES_PASSWORD=karrot
  - name: "redis"
    # Test performance: don't save to disk
    command: "redis-server --save '' --appendonly no"
    image: "redis:6-alpine"

steps:
  - name: "Test"
    image: "docker.io/karrot/python:3.1"
    environment:
      - MODE=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=karrot
      - DATABASE_USER=karrot
      - DATABASE_PASSWORD=karrot
      - REDIS_HOST=redis
      - SECRET_KEY=notverysecret
      # Test performance: use custom test settings
      - DJANGO_SETTINGS_MODULE=config.test_settings
    commands:
      - test -d env/bin || virtualenv -p python3 env
      - . env/bin/activate
      - ./sync.py
      - mkdir -p test-reports
      - pytest -n 4 --cov=karrot --cov-report xml --junitxml=test-reports/junit.xml
    when:
      branch: master

#  - name: "Build docker image"
#    image: woodpeckerci/plugin-docker-buildx
#    settings:
#      platforms: linux/amd64
#      repo: codeberg.org/${CI_REPO}
#      registry: codeberg.org
#      auto_tag: true
#      username: ${CI_REPO_OWNER}
#      password:
#        from_secret: cb_token
#    when:
#      - event: push
#        branch: master
#      - event: tag

