services:
  - name: database
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=karrot
      - POSTGRES_DB=karrot
      - POSTGRES_PASSWORD=karrot
  - name: redis
    image: "redis:6-alpine"

steps:
  - name: "Test"
    image: "codeberg.org/karrot/ci:796207fea50363b719ca6d5edaa497169988a07f"
    environment:
      - MODE=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=karrot
      - DATABASE_USER=karrot
      - DATABASE_PASSWORD=karrot
      - REDIS_HOST=redis
      - SECRET_KEY=notverysecret
    commands:
      - ./sync.py
      - mkdir -p test-reports
      - pytest -n $(nproc) --cov=karrot --cov-report xml --junitxml=test-reports/junit.xml
    when:
      - branch: master
      - event: tag

  - name: "Build docker image"
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      - event: push
        branch: master
      - event: tag
