# Generated by Django 2.1.2 on 2018-11-14 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170701_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='after',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='before',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
