# Generated by Django 2.1.4 on 2018-12-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20181216_2133'),
        ('history', '0005_auto_20181114_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='history',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.ActivitySeries'),
        ),
    ]
