# Generated by Django 2.1.5 on 2019-01-23 16:28

from django.db import migrations


def rewrite_to_participants(apps, schema_editor):
    History = apps.get_model('history', 'History')
    for h in History.objects.filter(payload__has_key='participant_ids'):
        h.payload['participants'] = h.payload['participant_ids']
        del h.payload['participant_ids']
        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20181216_2133'),
    ]

    operations = [migrations.RunPython(rewrite_to_participants, migrations.RunPython.noop, elidable=True)]
