# Generated by Django 2.2.6 on 2019-11-03 19:57

from django.db import migrations
import django_enumfield.db.fields
import karrot.history.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_extend_historic_data_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='typus',
            field=django_enumfield.db.fields.EnumField(enum=karrot.history.models.HistoryTypus),
        ),
    ]
