# Generated by Django 3.1.2 on 2020-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20191107_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='after',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='before',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
