# Generated by Django 3.1.4 on 2020-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20201108_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
