# Generated by Django 3.2.15 on 2022-09-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_rename_active_until_agreement_active_to'),
        ('history', '0013_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.agreement'),
        ),
    ]
