#!/usr/bin/env node

const find = require('find');
const { readFileSync, writeFileSync } = require('fs');
const mjml = require('mjml');
const path = require('path');
const BASEDIR = path.resolve(path.join(__dirname, '..'));

find.file(/\/templates\/[^_][^\/]*\.mjml$/, path.join(BASEDIR, 'foodsaving') , files => {
  files.forEach(file => {
    // process.chdir(path.dirname(file));
    const name = file.substring(BASEDIR.length + 1);
    const contents = readFileSync(file, 'utf8');
    try {
      const rendered = mjml.mjml2html(contents, {
        level: 'strict',
        filePath: file
      });
      const output = file.replace(/\.mjml$/, '.html.jinja2');
      console.log('converted', name, '->', '.html.jinja2');
      writeFileSync(output, rendered.html);
    } catch (err) {
      console.log(err);
    }
  });
})
