# Generated by Django 2.1.5 on 2019-02-12 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='message',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'option')},
        ),
    ]
