# Generated by Django 2.1.7 on 2019-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190212_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status_changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
