# Generated by Django 3.0.2 on 2020-01-22 20:30
from datetime import datetime

from django.db import migrations
from pytz import utc


def migrate(apps, schema_editor):
    NotificationMeta = apps.get_model('notifications', 'NotificationMeta')
    User = apps.get_model('users', 'User')

    for user in User.objects.filter(notificationmeta__isnull=True):
        NotificationMeta.objects.create(user=user, marked_at=datetime.min.replace(tzinfo=utc))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True)]
