# Generated by Django 3.0.2 on 2020-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_notification_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmeta',
            name='marked_at',
            field=models.DateTimeField(),
        ),
    ]
