# Generated by Django 3.0.2 on 2020-06-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_set_non-nullable_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmeta',
            name='marked_at',
            field=models.DateTimeField(),
        ),
    ]
