# Generated by Django 3.1.2 on 2020-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200615_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.JSONField(null=True),
        ),
    ]
