# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 23:42
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import foodsaving.conversations.models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20160721_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=enumfields.fields.EnumField(default=0, enum=foodsaving.conversations.models.ConversationType, max_length=10),
        ),
    ]
