# Generated by Django 2.0.3 on 2018-04-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_conversationmessage_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='updated_at',
        ),
    ]
