# Generated by Django 2.0.7 on 2018-07-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_auto_20180717_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationthreadparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationthreadparticipant',
            name='seen_up_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.ConversationMessage'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='conversations.ConversationMessage'),
        ),
    ]
