# Generated by Django 2.1 on 2018-08-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_groupmembership_added_by'),
        ('conversations', '0015_auto_20180728_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
