# Generated by Django 2.1 on 2018-08-22 18:07

import django.db.models.deletion
from django.db import migrations, models


def set_conversation_group(apps, schema_editor):
    # conversation.group has been removed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_groupmembership_added_by'),
        ('conversations', '0016_conversation_group'),
    ]

    operations = [migrations.RunPython(set_conversation_group, migrations.RunPython.noop, elidable=True)]
