# Generated by Django 2.1 on 2018-08-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_conversationmessage_latest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='group',
        ),
    ]
