# Generated by Django 2.0.3 on 2018-04-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_remove_conversationmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
