# Generated by Django 2.1 on 2018-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_remove_conversation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
