# Generated by Django 2.1.5 on 2019-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('conversations', '0022_fix_wrong_latest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
