# Generated by Django 2.1.5 on 2019-02-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_group_photo'),
        ('conversations', '0027_conversation_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_group_public',
            field=models.BooleanField(default=False),
        ),
    ]
