# Generated by Django 2.1.5 on 2019-02-05 15:54

from django.db import migrations


def set_conversation_group(apps, schema_editor):
    Conversation = apps.get_model('conversations', 'Conversation')
    i = 0
    for c in Conversation.objects.exclude(target_id=None).select_related('target_type'):
        target_type = c.target_type
        TargetModel = apps.get_model(target_type.app_label, target_type.model)
        target = TargetModel.objects.get(id=c.target_id)

        type = target_type.model
        group = None
        if type == 'pickupdate':
            group = target.place.group
        elif type == 'application' or type == 'issue' or type == 'place':
            group = target.group
        elif type == 'group':
            group = target

        if group is None:
            raise Exception('did not find group for conversation', c, 'has target type', type)

        c.group = group
        c.save(update_fields=['group'])

        i += 1
        if i % 10 == 0:
            print('.', end='', flush=True)
        if i % 1000 == 0:
            print(i, end='', flush=True)

    if i > 1000:
        print(i)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_group_photo'),
        ('conversations', '0028_auto_20190205_1558'),
    ]

    operations = [migrations.RunPython(set_conversation_group, migrations.RunPython.noop, elidable=True)]
