# Generated by Django 2.0.6 on 2018-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_conversationmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
