# Generated by Django 2.1.5 on 2019-01-07 07:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('conversations', '0024_auto_20190107_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='email_notifications',
        ),
    ]
