# Generated by Django 2.1.5 on 2019-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0026_conversationmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
