# Generated by Django 2.1.5 on 2019-02-10 12:29

from django.db import migrations


def set_conversation_is_group_public(apps, schema_editor):
    Conversation = apps.get_model('conversations', 'Conversation')
    public_conversations = []
    for c in Conversation.objects.exclude(target_id=None).select_related('target_type'):
        target_type = c.target_type.model
        if target_type != 'issue':
            public_conversations.append(c.id)

    Conversation.objects.filter(id__in=public_conversations).update(is_group_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0029_set_conversation_group'),
    ]

    operations = [migrations.RunPython(set_conversation_is_group_public, migrations.RunPython.noop, elidable=True)]
