# Generated by Django 2.2.1 on 2019-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0031_convert_message_reactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmeta',
            old_name='marked_at',
            new_name='conversations_marked_at',
        ),
    ]
