# Generated by Django 3.0.2 on 2020-01-22 20:37

from datetime import datetime

from django.db import migrations
from pytz import utc


def migrate(apps, schema_editor):
    ConversationMeta = apps.get_model('conversations', 'ConversationMeta')
    User = apps.get_model('users', 'User')

    min_date = datetime.min.replace(tzinfo=utc)

    for user in User.objects.filter(conversationmeta__isnull=True):
        ConversationMeta.objects.create(user=user, conversations_marked_at=min_date, threads_marked_at=min_date)


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0035_auto_20200405_1938'),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True)]
