# Generated by Django 3.0.2 on 2020-06-15 13:11
from datetime import datetime

from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0036_add_conversation_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmeta',
            name='conversations_marked_at',
            field=models.DateTimeField(default=datetime.min.replace(tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversationmeta',
            name='threads_marked_at',
            field=models.DateTimeField(default=datetime.min.replace(tzinfo=utc)),
            preserve_default=False,
        ),
    ]
