# Generated by Django 3.0.2 on 2020-06-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0038_auto_20200615_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_group_public',
        ),
    ]
