# Generated by Django 3.0.7 on 2020-07-20 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0039_remove_conversation_is_group_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessageImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='conversation_message_images', verbose_name='ConversationMessage Image')),
                ('position', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='conversations.ConversationMessage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
