# Generated by Django 4.2.1 on 2023-06-23 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0041_conversationmessagemention"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMessageAttachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.FileField(
                        upload_to="conversation_message_attachment_files",
                        verbose_name="ConversationMessage Attachment",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        null=True, upload_to="conversation_message_attachment_previews"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        null=True,
                        upload_to="conversation_message_attachment_thumbnails",
                    ),
                ),
                ("filename", models.CharField(max_length=255, null=True)),
                ("position", models.IntegerField(default=0)),
                ("content_type", models.CharField(max_length=120, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="conversations.conversationmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
