# Generated by Django 3.2.10 on 2022-01-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0041_conversationmessagemention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessagemention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
