# Generated by Django 3.2.15 on 2023-04-24 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0041_conversationmessagemention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessageAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, default='', upload_to='conversation_message_images', verbose_name='ConversationMessage Image')),
                ('file', models.FileField(blank=True, default='', upload_to='conversation_message_files', verbose_name='ConversationMessage File')),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=120, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversationmessage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='ConversationMessageImage',
        ),
        migrations.AddConstraint(
            model_name='conversationmessageattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('image', ''), models.Q(('file', ''), _negated=True)), models.Q(('file', ''), models.Q(('image', ''), _negated=True)), _connector='OR'), name='conversations_conversationmessageattachment_image_or_file'),
        ),
    ]
