# Generated by Django 3.2.15 on 2023-04-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0041_conversationmessagemention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessageAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to='conversation_message_attachments', verbose_name='ConversationMessage Attachment')),
                ('position', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=120, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversationmessage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
