# Generated by Django 3.2.15 on 2023-04-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0041_conversationmessagemention'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationMessageImage',
            new_name='ConversationMessageAttachment',
        ),
    ]
