# Generated by Django 3.2.15 on 2023-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0042_conversationmessageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessageattachment',
            name='file',
            field=models.FileField(upload_to='conversation_message_attachments', verbose_name='ConversationMessage Attachment'),
        ),
    ]
