# Generated by Django 3.2.15 on 2023-04-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0042_rename_conversationmessageimage_conversationmessageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversationmessage'),
        ),
    ]
