# Generated by Django 3.2.15 on 2023-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0043_alter_conversationmessageattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessageattachment',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
