# Generated by Django 4.2.7 on 2024-01-25 14:19

from django.db import migrations, models
import karrot.base.base_models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0043__cleanup_conversation_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessageattachment',
            name='file',
            field=models.FileField(upload_to=karrot.base.base_models.UploadToUUID('conversation_message_attachment_files'), verbose_name='ConversationMessage Attachment'),
        ),
        migrations.AlterField(
            model_name='conversationmessageimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=karrot.base.base_models.UploadToUUID('conversation_message_images'), verbose_name='ConversationMessage Image'),
        ),
    ]
