# Generated by Django 4.2.7 on 2024-03-06 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0044_alter_conversationmessageattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmeta',
            name='conversations_marked_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversationmeta',
            name='threads_marked_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
