# Generated by Django 3.2.15 on 2023-05-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0045_auto_20230516_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessageattachment',
            old_name='file_preview',
            new_name='preview',
        ),
        migrations.RenameField(
            model_name='conversationmessageattachment',
            old_name='file_thumbnail',
            new_name='thumbnail',
        ),
    ]
