# Generated by Django 4.2.1 on 2023-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0046_auto_20230516_1103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessageattachment",
            name="file",
            field=models.FileField(
                upload_to="conversation_message_attachment_files",
                verbose_name="ConversationMessage Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessageattachment",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="conversation_message_attachment_previews"
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessageattachment",
            name="thumbnail",
            field=models.ImageField(
                null=True, upload_to="conversation_message_attachment_thumbnails"
            ),
        ),
    ]
