version: "3"
services:

  db:
    image: "docker.io/postgres:13.11"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: db

  redis:
    image: "docker.io/redis:6.2.6-alpine"
    restart: "unless-stopped"
    ports:
      - "6379:6379"

volumes:
  db:
    name: ${DB_VOLUME_NAME:-db}
