apiVersion: v1
kind: Pod
metadata:
  name: karrot-services
spec:
  containers:

  - name: db
    image: docker.io/postgres:16.2-alpine
    args:
      - "-c"
      - "fsync=off"
      - "-c"
      - "full_page_writes=off"
    env:
    - name: POSTGRES_USER
      value: db
    - name: POSTGRES_PASSWORD
      value: db
    - name: POSTGRES_DB
      value: db
    ports:
    - containerPort: 5432
      hostPort: 5432
      protocol: TCP
    volumeMounts:
    - name: db
      mountPath: /var/lib/postgresql/data

  - name: redis
    image: docker.io/redis:6.2.6-alpine
    ports:
    - containerPort: 6379
      hostPort: 6379
      protocol: TCP

  - name: maildev
    image: docker.io/maildev/maildev:2.1.0
    ports:
    - containerPort: 1080
      hostPort: 1080
      protocol: TCP
    - containerPort: 1025
      hostPort: 1025
      protocol: TCP

  - name: pgweb
    image: docker.io/sosedoff/pgweb:0.14.3
    env:
    - name: DATABASE_URL
      value: postgres://db:db@db:5432/db?sslmode=disable
    ports:
    - containerPort: 8081
      hostPort: 5050
      procotol: TCP

  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: karrot-db
