# Generated by Django 2.1.5 on 2019-01-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='opened_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('ongoing', 'ongoing'), ('decided', 'decided')], default='ongoing'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.TextField(choices=[('conflict_resolution', 'conflict_resolution')], default='conflict_resolution'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.TextField(choices=[('custom', 'custom'), ('further_discussion', 'further_discussion'), ('remove_user', 'remove_user')], default='custom'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='status',
            field=models.TextField(choices=[('ongoing', 'ongoing'), ('decided', 'decided')], default='ongoing'),
        ),
    ]
