# Generated by Django 2.1.5 on 2019-01-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='mean_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='accepted_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_voting', to='cases.Option'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
