# Generated by Django 2.1.5 on 2019-01-09 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_auto_20190109_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='affected_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_by_case', to=settings.AUTH_USER_MODEL),
        ),
    ]
