# Generated by Django 2.1.5 on 2019-01-09 16:09

from django.db import migrations, models
import foodsaving.cases.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_affected_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='expires_at',
            field=models.DateTimeField(default=foodsaving.cases.models.voting_expiration_time),
        ),
    ]
