# Generated by Django 2.1.5 on 2019-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190112_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_decided',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('ongoing', 'ongoing'), ('decided', 'decided'), ('cancelled', 'cancelled')], default='ongoing'),
        ),
    ]
