# Generated by Django 2.1.5 on 2019-01-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_auto_20190118_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='participants',
            field=models.ManyToManyField(related_name='cases', through='cases.CaseParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
