# Generated by Django 2.1.5 on 2019-01-19 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_auto_20190119_1222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'user')},
        ),
    ]
