# Generated by Django 2.1.5 on 2019-01-19 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0036_group_photo'),
        ('cases', '0006_auto_20190119_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='GroupCase',
        ),
    ]
