# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 23:42
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import foodsaving.history.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20170225_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='typus',
            field=enumfields.fields.EnumField(enum=foodsaving.history.models.HistoryTypus, max_length=10),
        ),
    ]
