# Generated by Django 2.2.6 on 2019-11-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.Offer'),
        ),
    ]
