# Generated by Django 2.2.7 on 2019-11-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20191105_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerimage',
            options={'ordering': ['position']},
        ),
    ]
