# Generated by Django 3.0.2 on 2020-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_convert_accepted_offers_to_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=100),
        ),
    ]
