# Generated by Django 4.2.1 on 2023-10-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_set_archived_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
