# Generated by Django 4.2.7 on 2024-01-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_remove_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status_changed_at',
        ),
    ]
