# Generated by Django 4.2.7 on 2024-01-25 14:19

from django.db import migrations
import karrot.base.base_models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_offer_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=karrot.base.base_models.UploadToUUID('offer_images'), verbose_name='Offer Image'),
        ),
    ]
