{
 "title": "Activity",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Offers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New offers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "offer_created" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Offers accepted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "offer_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Offers archived",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "offer_archived" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stores, Activities and Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Activities done",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "activity_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Activities missed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "activity_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Users that did an activity in last 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count_activity_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active store cooperations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.group.places",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count_status_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Feedback given",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "feedback" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Active users that did an activity (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "query": "SELECT last(\"count_activity_active_7d\") / last(\"count_active_7d\") * 100 FROM \"karrot.users\" WHERE $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "count_activity_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Group messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "group" },
      { "condition": "AND", "key": "is_reply", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Group replies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "is_reply", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Activity messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "activity" },
      { "condition": "AND", "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Application messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "application" }
     ]
    }
   ]
  },
  {
   "title": "Private messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "private" }
     ]
    }
   ]
  },
  {
   "title": "Reactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message_reaction" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "!=", "value": "inactive" },
      { "condition": "AND", "key": "group_status", "operator": "!=", "value": "playground" }
     ]
    }
   ]
  },
  {
   "title": "Place messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "place" },
      { "condition": "AND", "key": "is_reply", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "Place replies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "place" },
      { "condition": "AND", "key": "is_reply", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Offer messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"activity_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "offer" }
     ]
    }
   ]
  },
  { "title": "Applications & Invitations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Applications created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_pending" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Applications accepted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Invitations sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "invitation_created" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Invitations accepted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "invitation_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "New users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_auth_user_create",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group joins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group leaves",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_left" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Marked as inactive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.periodic",
     "select": [
      [
       { "params": [ "count_users_flagged_inactive" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trust given",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "trust_given" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users (1d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_active_1d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users (30d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_active_30d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users (60d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_active_60d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users (90d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_active_90d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity active users (1d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_activity_active_1d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity active users (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_activity_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity active users (30d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_activity_active_30d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity active users (60d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_activity_active_60d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity active users (90d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.users",
     "select": [
      [
       { "params": [ "count_activity_active_90d" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Tech stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Websocket messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "websocket_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Browser push messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "subscription_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "web" }
     ]
    }
   ]
  },
  {
   "title": "Android push messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "subscription_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "android" }
     ]
    }
   ]
  },
  {
   "title": "FCM push errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "subscription_push_error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emails sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.email.sent",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Email errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.email.error",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming emails rejected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "incoming_email_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User activity",
   "type": "singlestat",
   "description": "Arbitrary number that roughly correlates with the time the user spends clicking around",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 36 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_activity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API write reponse time (95th percentile)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 39 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "PATCH" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "POST" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "PUT" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  {
   "title": "API read reponse time (95th percentile)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 39 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Group leaderboard",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"group_activity\") AS \"page impressions\", sum(\"activity_joined\") AS \"activities joined\", sum(\"activity_done\") AS \"activities done\", sum(\"activity_missed\") AS \"activities missed\", sum(\"feedback\") AS \"feedbacks given\", sum(\"message\") AS \"messages written\", sum(\"message_reaction\") AS \"message reactions\", sum(\"group_joined\") AS \"new members\" FROM \"karrot.events\" WHERE $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "group_activity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activity" ], "type": "alias" }
      ],
      [
       { "params": [ "message_reaction" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "reactions" ], "type": "alias" }
      ],
      [
       { "params": [ "activity_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities joined" ], "type": "alias" }
      ],
      [
       { "params": [ "group_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "members joined" ], "type": "alias" }
      ],
      [
       { "params": [ "activity_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities done" ], "type": "alias" }
      ],
      [
       { "params": [ "activity_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities missed" ], "type": "alias" }
      ],
      [
       { "params": [ "feedback" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "feedback" ], "type": "alias" }
      ],
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "messages" ], "type": "alias" }
      ],
      [
       { "params": [ "offer_created" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "offers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Active in last week (with >3 active users)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "group $tag_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.group.members",
     "select": [
      [
       { "params": [ "count_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "count_active_7d", "operator": ">", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Group Names",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT id, name FROM group_names"
    }
   ]
  },
  {
   "title": "Group Activity",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.group.members",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_1d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 1d" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 7d" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 30d" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}