{
 "title": "Emails",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Emails sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "recipient count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.sent",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emails per category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "recipient count",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "karrot.email.sent",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity notification stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col [group=$tag_group]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.activity_notification",
     "select": [
      [
       { "params": [ "tomorrow_empty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow empty" ], "type": "alias" }
      ],
      [
       { "params": [ "tomorrow_not_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow not full" ], "type": "alias" }
      ],
      [
       { "params": [ "tomorrow_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow user" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_empty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight empty" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_not_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight not full" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight user" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group Summary notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "group $tag_group $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.group_summary",
     "select": [
      [
       { "params": [ "email_recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "recipients" ], "type": "alias" }
      ],
      [
       { "params": [ "feedback_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "feedback" ], "type": "alias" }
      ],
      [
       { "params": [ "message_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "messages" ], "type": "alias" }
      ],
      [
       { "params": [ "new_user_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "new users" ], "type": "alias" }
      ],
      [
       { "params": [ "activities_done_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities done" ], "type": "alias" }
      ],
      [
       { "params": [ "activities_missed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities missed" ], "type": "alias" }
      ],
      [
       { "params": [ "activities_missed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activities missed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "recipient count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.error",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors per category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "recipient count",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "karrot.email.error",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}