{
 "title": "frontend stats",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "logged out / first load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "logged out / not first load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "logged in / first load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "logged in / not first load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "pages (logged out)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_route_name (first load)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "False" }
     ]
    },
    {
     "alias": "$tag_route_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "pages (logged in)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_route_name (first load)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "$tag_route_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "first_load", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "browser",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_browser",
     "groupBy": [
      { "params": [ "browser" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "query": "SELECT count(\"ms\") FROM \"karrot.stats.frontend\" WHERE $timeFilter GROUP BY \"browser\"",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "mobile",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_mobile",
     "groupBy": [
      { "params": [ "mobile" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "query": "SELECT count(\"ms\") FROM \"karrot.stats.frontend\" WHERE $timeFilter GROUP BY \"browser\"",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "os",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_os",
     "groupBy": [
      { "params": [ "os" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "query": "SELECT count(\"ms\") FROM \"karrot.stats.frontend\" WHERE $timeFilter GROUP BY \"browser\"",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "logged in",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_logged_in",
     "groupBy": [
      { "params": [ "logged_in" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "query": "SELECT count(\"ms\") FROM \"karrot.stats.frontend\" WHERE $timeFilter GROUP BY \"browser\"",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "first load leaderboard by route name",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "$tag_route_name",
     "groupBy": [
      { "params": [ "route_name" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "first_load", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "first load leaderboard by group id",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.stats.frontend",
     "query": "SELECT \"ms\" FROM \"karrot.stats.frontend\" WHERE (\"dev\" = 'False' AND \"first_load\" = 'True' AND \"group\" <> '') AND $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dev", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "first_load", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "logged_in", "operator": "=", "value": "True" }
     ]
    }
   ]
  }
 ]
}