{
 "title": "Issues",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Issues created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "issue_created" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Votes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "issue_vote" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Votes changed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "issue_vote_changed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Votes deleted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "issue_vote_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group Issue stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT \nlast(\"count_ongoing\") AS \"ongoing\", \nlast(\"count_cancelled\") AS \"cancelled\", \nlast(\"count_decided\") AS \"decided\"\nFROM \"karrot.group.issues\" WHERE $timeFilter AND (\"count_ongoing\" > 0 OR \"count_decided\" > 0 OR \"count_cancelled\" > 0) GROUP BY \"group\" fill(0)",
     "select": [
      [
       { "params": [ "application_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "accepted" ], "type": "alias" }
      ],
      [
       { "params": [ "application_declined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "declined" ], "type": "alias" }
      ],
      [
       { "params": [ "application_pending" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "new" ], "type": "alias" }
      ],
      [
       { "params": [ "application_withdrawn" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "withdrawn" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total issues per group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "group $tag_group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.group.issues",
     "query": "SELECT \"count_total\"\nFROM \"karrot.group.issues\" WHERE $timeFilter AND (\"count_ongoing\" > 0 OR \"count_decided\" > 0 OR \"count_cancelled\" > 0) GROUP BY \"group\" fill(0)",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "count_total", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}