{
 "title": "Notifications",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Notifications created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "notification_created" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Notifications clicked",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "notification_clicked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Clicked within",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "notification_clicked_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "% clicked",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"notification_clicked\") / sum(\"notification_created\") FROM \"karrot.events\" WHERE (\"group_status\" = 'active') AND $timeFilter",
     "select": [
      [
       { "params": [ "notification_clicked_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "By Group",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"notification_created\") AS \"created\", sum(\"notification_clicked\") AS \"clicked\", mean(\"notification_clicked_seconds\") AS \"clicked within\", sum(\"notification_clicked\") / sum(\"notification_created\")  AS \"% clicked\" FROM \"karrot.events\" WHERE (\"group_status\" = 'active') AND $timeFilter GROUP BY \"group\" fill(0)",
     "select": [
      [
       { "params": [ "notification_created" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "created" ], "type": "alias" }
      ],
      [
       { "params": [ "notification_clicked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "clicked" ], "type": "alias" }
      ],
      [
       { "params": [ "notification_clicked_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "clicked within" ], "type": "alias" }
      ],
      [
       { "params": [ "notification_clicked_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% clicked" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "By Type",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "notification_type" ], "type": "tag" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"notification_created\") AS \"created\", sum(\"notification_clicked\") AS \"clicked\", mean(\"notification_clicked_seconds\") AS \"clicked within\", sum(\"notification_clicked\") / sum(\"notification_created\")  AS \"% clicked\"  FROM \"karrot.events\" WHERE (\"group_status\" = 'active') AND $timeFilter GROUP BY \"notification_type\" fill(0)",
     "select": [
      [
       { "params": [ "notification_created" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "created" ], "type": "alias" }
      ],
      [
       { "params": [ "notification_clicked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "clicked" ], "type": "alias" }
      ],
      [
       { "params": [ "notification_clicked_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "clicked within" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}