{
 "title": "User level and trust stats",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Trust given",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "trust_given" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "New editors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "member_became_editor" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Group stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "member_became_editor" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "new editors" ], "type": "alias" }
      ],
      [
       { "params": [ "trust_given" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "trust" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Active memberships in groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.group.members",
     "query": "SELECT \nlast(\"count_active_30d\") AS \"members\", \nlast(\"count_active_editors_30d\") AS \"editors\", \nlast(\"count_active_newcomers_30d\") AS \"newcomers\",\nlast(\"count_active_editors_30d\") / last(\"count_active_30d\") AS \"percent editors\"\nFROM \"karrot.group.members\" WHERE (\"group_status\" = 'active') AND $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "count_active_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "members" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_editors_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "editors" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_newcomers_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "newcomers" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trust per day and group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "trust_given" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Active newcomers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.group.members",
     "select": [
      [
       { "params": [ "count_active_newcomers_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group_status", "operator": "=", "value": "active" }
     ]
    }
   ]
  }
 ]
}