{
 "title": "yuca",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Redis connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Karrot CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "huey" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "python" },
      { "condition": "AND", "key": "user", "operator": "=", "value": "karrot-world" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "daphne" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "daphne" },
      { "condition": "AND", "key": "user", "operator": "=", "value": "karrot-world" }
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated file handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "linux_sysctl_fs",
     "select": [
      [
       { "params": [ "file-nr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sda" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sda" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sdb" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1min" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15min" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}