# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20161211_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('rule', models.TextField()),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_date_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_max_participants_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='weeks_in_advance',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities',
                                    to='places.Place'),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series',
                                    to='places.Place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='activities', to='places.ActivitySeries'),
        ),
    ]
