# Generated by Django 1.11.4 on 2017-08-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_feedback'),
        ('places', '0016_activity_done_and_processed'),
    ]

    operations = [
    ]
