# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0027_auto_20171031_0942'),
    ]

    # Rename the database tables that refer to the models Activity,
    # ActivitySeries and Feedback.
    database_operations = [
        migrations.AlterModelTable('activity', 'activities_activity'),
        migrations.AlterModelTable('activityseries', 'activities_activityseries'),
        migrations.AlterModelTable('feedback', 'activities_feedback'),
    ]

    # Delete the models Activity, ActivitySeries and Feedback.
    # They will be re-created in the new activities app.
    state_operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='about',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='series',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='place',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='place',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivitySeries',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
