# Generated by Django 2.2 on 2019-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0033_auto_20190130_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='public_description',
            field=models.TextField(blank=True),
        ),
    ]
