# Generated by Django 3.2.5 on 2021-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0036_make_place_type_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
