# Generated by Django 3.1.7 on 2021-03-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0037_add_standard_place_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.placetype'),
        ),
        migrations.AlterField(
            model_name='place',
            name='status_next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.placestatus'),
        ),
    ]
