# Generated by Django 3.2.7 on 2021-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0037_alter_placetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='default_view',
            field=models.CharField(choices=[('activities', 'Activities'), ('wall', 'Wall')], default='activities', max_length=20),
        ),
    ]
