# Generated by Django 3.1.7 on 2021-03-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0038_make_place_type_and_status_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='status',
            new_name='status_old',
        ),
    ]
