# Generated by Django 3.1.7 on 2021-03-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0039_rename_old_status_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='status_next',
            new_name='status',
        ),
    ]
