# Generated by Django 4.2.1 on 2023-10-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0040_set_place_archived_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetype',
            name='status',
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('negotiating', 'Negotiating'), ('active', 'Active'), ('declined', 'Declined')], default='created', max_length=20),
        ),
    ]
