# Generated by Django 4.2.1 on 2023-10-27 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0050_enable_agreements_and_participant_types'),
        ('places', '0042_alter_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PlaceStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('name_is_translatable', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('colour', models.CharField(max_length=6)),
                ('show_on_map', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_statuses', to='groups.group')),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='place',
            name='status_next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.placestatus'),
        ),
    ]
