# Generated by Django 4.2.1 on 2023-10-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0044_migrate_place_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
    ]
