# Generated by Django 4.2.1 on 2023-10-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0045_remove_place_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='status_next',
            new_name='status',
        ),
    ]
