# Generated by Django 4.2.7 on 2023-11-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0046_rename_status_next_place_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placestatus',
            old_name='show_on_map',
            new_name='visible',
        ),
    ]
