# Generated by Django 4.2.7 on 2023-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0047_rename_show_on_map_placestatus_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='placestatus',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
