# Generated by Django 4.2.7 on 2023-11-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0048_placestatus_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placestatus',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
