# Generated by Django 4.2.7 on 2023-11-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0049_rename_visible_placestatus_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placestatus',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='placestatus',
            name='order',
            field=models.CharField(blank=True),
        ),
    ]
