# Generated by Django 4.2.7 on 2023-11-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0050_alter_placestatus_options_placestatus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placestatus',
            options={'ordering': ['order', 'id']},
        ),
    ]
