# Generated by Django 4.2.7 on 2023-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0052_set_place_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placestatus',
            name='order',
            field=models.CharField(),
        ),
    ]
