# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:15
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='user_profile_photos/', verbose_name='Photo'),
        ),
    ]
