# Generated by Django 2.0.1 on 2018-01-12 10:38

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_verification_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='uploads/user__photos/',
                                                                 verbose_name='Photo'),
        ),
    ]
