# Generated by Django 2.0.1 on 2018-02-18 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180218_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust',
            name='level',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='trust',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trust',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
