# Generated by Django 2.0.7 on 2018-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_groupapplication_decided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapplication',
            name='decided_at',
            field=models.DateTimeField(null=True),
        ),
    ]
