# Generated by Django 2.1.5 on 2019-01-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_groupapplication_decided_at'),
    ]

    operations = [
        migrations.RenameModel('GroupApplication', 'Application'),
    ]
