# Generated by Django 2.1.5 on 2019-01-25 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190123_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decided', to=settings.AUTH_USER_MODEL),
        ),
    ]
