# Generated by Django 1.9.7 on 2016-07-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = []
