# Generated by Django 3.2.10 on 2021-12-30 23:54
import random
import string

from django.db import migrations, models, IntegrityError, transaction


def try_options(user, options, n=None):
    for option in options:
        try:
            user.username = option + (str(n) if n else '')
            with transaction.atomic():
                user.save()
            return
        except IntegrityError:
            continue
    n = n + 1 if n else 1
    if n > 1000:
        raise Exception('I give up!')
    return try_options(user, options, n)


def random_username():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))


def generate_usernames(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.order_by('-last_login'):
        options = []
        if user.display_name:
            options.append(user.display_name.split(' ')[0].lower())
            options.append(user.display_name.replace(' ', '').lower())
        if user.email:
            options.append(user.email.split('@')[0].lower())
        if not options:
            options.append(random_username())
        try_options(user, options)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_username'),
    ]

    operations = [
        migrations.RunPython(generate_usernames, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
