# Generated by Django 3.2.10 on 2022-01-20 11:44

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations
import karrot.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_username'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True),
        ),
    ]
