# Generated by Django 4.2.7 on 2024-01-25 14:19

from django.db import migrations
import karrot.base.base_models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_fix_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to=karrot.base.base_models.UploadToUUID('user__photos'), verbose_name='Photo'),
        ),
    ]
