# Generated by Django 3.2.4 on 2021-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_auto_20201108_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='event_id',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_id'], name='webhooks_em_event_i_16b408_idx'),
        ),
    ]
