version: '3.8'
services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
     - certs:/certs
    expose:
    - 2375
    - 2376


  build:
    image: docker
    command: "sh -c 'sleep 5 && echo hello && docker ps'"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    volumes:
    - /home/nick/Projects/karrot/karrot-backend:/app 
    - certs:/certs

volumes:
  certs:
