# Generated by Django 1.9.7 on 2016-08-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20160728_1725'),
    ]

    operations = [
    ]
