# Generated by Django 2.0.7 on 2018-07-15 10:40

from django.db import migrations


class GroupNotificationType(object):
    WEEKLY_SUMMARY = 'weekly_summary'
    DAILY_ACTIVITY_NOTIFICATION = 'daily_activity_notification'
    NEW_APPLICATION = 'new_application'


def enable_new_application_notifications(apps, schema_editor):
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for membership in GroupMembership.objects.all():
        if GroupNotificationType.NEW_APPLICATION not in membership.notification_types:
            membership.notification_types.append(GroupNotificationType.NEW_APPLICATION)
            membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_group_application_defaults_20180715_1040'),
    ]

    operations = [
        migrations.RunPython(enable_new_application_notifications, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
