# Generated by Django 2.1.7 on 2019-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
