# Generated by Django 2.2.1 on 2019-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0038_remove_group_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='theme',
            field=models.TextField(choices=[('foodsaving', 'foodsaving'), ('bikekitchen', 'bikekitchen')], default='foodsaving'),
        ),
    ]
