# Generated by Django 2.2.5 on 2019-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0039_group_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='theme',
            field=models.TextField(choices=[('foodsaving', 'foodsaving'), ('bikekitchen', 'bikekitchen'), ('general', 'general')], default='foodsaving'),
        ),
    ]
