# Generated by Django 3.0.5 on 2020-05-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0041_group_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='theme',
            field=models.TextField(choices=[('foodsaving', 'foodsaving'), ('bikekitchen', 'bikekitchen'), ('general', 'general')]),
        ),
    ]
