# Generated by Django 3.0.7 on 2020-07-17 13:25

import django.contrib.postgres.fields
from django.db import migrations, models
import karrot.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0042_auto_20200507_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=karrot.groups.models.default_group_features, size=None),
        ),
    ]
