# Generated by Django 3.2.5 on 2021-07-14 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0043_auto_20200717_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust',
            name='role',
            field=models.CharField(default='editor', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='trust',
            unique_together={('membership', 'given_by', 'role')},
        ),
    ]
