# Generated by Django 3.2.13 on 2022-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0043_auto_20200717_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_email_visible',
            field=models.BooleanField(default=True),
        ),
    ]
