# Generated by Django 3.2.10 on 2022-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0043_auto_20200717_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='information',
        ),
    ]
