# Generated by Django 3.2.7 on 2021-11-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0045_alter_groupmembership_roles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(check=models.Q(('roles__contains', ['member'])), name='must_have_member_role'),
        ),
    ]
