# Generated by Django 3.2.15 on 2022-09-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0047_add_group_newcomer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragreement',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='active_agreement',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='UserAgreement',
        ),
    ]
