# Generated by Django 3.2.15 on 2022-09-21 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0047_add_group_newcomer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='trusted_by',
        ),
        migrations.AddField(
            model_name='trust',
            name='role',
            field=models.CharField(default='editor', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='trust',
            unique_together={('membership', 'given_by', 'role')},
        ),
    ]
