# Generated by Django 3.2.15 on 2022-09-22 18:42

import django.contrib.postgres.fields
from django.db import migrations, models
import karrot.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0048_trust_for_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
