# Generated by Django 3.2.15 on 2022-09-30 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0048_auto_20220926_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='trusted_by',
        ),
        migrations.AddField(
            model_name='trust',
            name='role',
            field=models.CharField(default='editor', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='trust',
            unique_together={('membership', 'given_by', 'role')},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.TextField()),
                ('description', models.TextField()),
                ('threshold', models.IntegerField(default=1)),
                ('role_required_for_trust', models.CharField(max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='groups.group')),
            ],
            options={
                'unique_together': {('name', 'group')},
            },
        ),
    ]
