# Generated by Django 3.2.15 on 2022-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0049_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_required_for_trust',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
