# Generated by Django 3.2.15 on 2023-04-24 11:24
from django.contrib.postgres.operations import CITextExtension, BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        BtreeGistExtension(),
    ]
