# Generated by Django 3.2.15 on 2022-09-26 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import karrot.conversations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0048_auto_20220926_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_proposals', to='groups.group')),
                ('replace_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_proposals', to='agreements.agreement')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, karrot.conversations.models.ConversationMixin),
        ),
    ]
