# Generated by Django 3.2.15 on 2022-09-27 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0048_auto_20220926_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(null=True)),
                ('review_at', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
