# Generated by Django 3.2.15 on 2022-09-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
