# Generated by Django 3.2.15 on 2022-09-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_alter_agreement_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementproposal',
            name='agreement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement'),
        ),
        migrations.AlterField(
            model_name='agreementproposal',
            name='replace_agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_proposal', to='agreements.agreement'),
        ),
    ]
