# Generated by Django 3.2.15 on 2022-09-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20220928_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='active_until',
            new_name='active_to',
        ),
    ]
