# Generated by Django 3.2.15 on 2022-09-26 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0048_auto_20220926_2158'),
        ('agreements', '0003_auto_20220926_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreementproposal',
            old_name='replace_agreement',
            new_name='existing_agreement',
        ),
        migrations.RenameField(
            model_name='agreementproposal',
            old_name='agreement',
            new_name='new_agreement',
        ),
        migrations.RemoveField(
            model_name='agreementproposal',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='agreement',
            name='supersedes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement'),
        ),
        migrations.AddField(
            model_name='agreementproposal',
            name='supersedes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreementproposal'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
