# Generated by Django 2.1.1 on 2018-09-19 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20180915_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmeta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationmeta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
