# Generated by Django 2.1.1 on 2018-09-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180919_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='clicked_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
