# Generated by Django 4.2.7 on 2024-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomparticipant',
            name='unique_room_user',
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='identity',
            field=models.CharField(default='foo', unique=True),
            preserve_default=False,
        ),
    ]
