# Generated by Django 4.2.7 on 2024-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_remove_roomparticipant_unique_room_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.CharField(default='foo', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
