# Generated by Django 4.2.7 on 2024-01-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_room_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
