# Generated by Django 4.2.7 on 2024-01-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0050_enable_agreements_and_participant_types'),
        ('meet', '0004_remove_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meet_rooms', to='groups.group'),
            preserve_default=False,
        ),
    ]
