# Generated by Django 4.2.7 on 2024-01-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0050_enable_agreements_and_participant_types'),
        ('meet', '0005_room_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meet_rooms', to='groups.group'),
        ),
    ]
