# Generated by Django 4.2.7 on 2024-01-11 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0006_alter_room_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subject_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
