# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_permissions': []},
        ),
    ]
