#!/bin/bash

set -eu

if test -f config/local_settings.py; then
  echo "Please move your config/local_settings.py file before packaging as this is probably not what you want to be doing..."
  exit 1
fi

output_filename="${1:-karrot-backend.pyz}"

echo "building $output_filename"

# get path to site packages dir
# see https://stackoverflow.com/a/46071447
site_packages=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')

git rev-parse HEAD > karrot/COMMIT

python manage.py collectstatic --noinput

shiv --output-file="$output_filename" \
     --site-packages="$site_packages" \
     --python="/usr/bin/env python3" \
     --entry-point=karrot.cli:run \
     --preamble=scripts/shiv-cleanup.py \
     --no-deps .
