#!/bin/bash

set -eu

start_services() {
  (cd scripts/services && podman kube play services.yml --replace)
}

stop_services() {
  (cd scripts/services && podman kube down services.yml)
}

on_exit() {
  echo
  read -p "Do you want to stop the services? " -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo " ★ Stopping services"
    echo
    stop_services
  fi
}

trap on_exit EXIT

if [[ $(podman pod ps --format '{{.Status}}' --filter "name=karrot-services") != "Running" ]]; then
  echo
  echo " ★ Starting services"
  echo
  start_services
fi

echo
echo " ★ Starting application"
echo
honcho --procfile scripts/Procfile start
