#!/bin/bash

# runs whatever you pass either locally or via docker-compose if available

set -eu

if docker-compose ps >/dev/null 2>&1; then
  docker-compose exec --no-TTY backend "$@"
else
  "$@"
fi
