#!/bin/bash

set -eu

if ! podman pod exists karrot-services; then
  echo "Services not running!"
  echo
  echo "You can run ./scripts/dev to start everything"
  echo "Or ./scripts/services/start for just the services"
  exit 1
fi

podman exec -it karrot-services-db psql -U db "$@"
