# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django_enumfield.db.fields
from django_enumfield import enum

import karrot.subscriptions.models


class PushSubscriptionPlatformLegacy(enum.Enum):
    ANDROID = 1


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=django_enumfield.db.fields.EnumField(default=1,
                                                       enum=PushSubscriptionPlatformLegacy),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('user', 'token')},
        ),
    ]
