# Generated by Django 4.2.1 on 2023-09-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_webpushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='p256dh',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='keys',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='mobile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='os',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='version',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='browser',
            field=models.CharField(),
        ),
    ]
