# Generated by Django 4.2.1 on 2023-10-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_webpushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
