# Generated by Django 2.0.6 on 2018-06-28 12:19

from django.db import migrations, models


def convert_enum_to_char(apps, schema_editor):
    PushSubscription = apps.get_model('subscriptions', 'PushSubscription')
    PushSubscription.objects.filter(platform='1').update(platform='android')


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_channelsubscription_away_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='platform',
            field=models.CharField(choices=[('android', 'android'), ('web', 'web')], default='android', max_length=100),
        ),
        migrations.RunPython(convert_enum_to_char),
    ]
