# Generated by Django 2.1.2 on 2018-11-22 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickups', '0004_pickupdatecollector_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdate',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pickupdate',
            name='cancelled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_cancelled', to=settings.AUTH_USER_MODEL),
        ),
    ]
