# Generated by Django 2.1.2 on 2018-11-23 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickups', '0005_auto_20181122_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupdate',
            old_name='cancelled_by',
            new_name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='pickupdate',
            name='is_date_changed',
        ),
        migrations.RemoveField(
            model_name='pickupdate',
            name='is_description_changed',
        ),
        migrations.RemoveField(
            model_name='pickupdate',
            name='is_max_collectors_changed',
        ),
        migrations.AddField(
            model_name='pickupdate',
            name='last_changed_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pickupdateseries',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupdateseries',
            name='last_changed_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pickupdateseries',
            name='pickups_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
