# Generated by Django 2.1.2 on 2018-11-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0006_auto_20181123_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupdateseries',
            old_name='pickups_updated_at',
            new_name='pickups_created_until',
        ),
    ]
