# Generated by Django 2.1.2 on 2018-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0007_auto_20181123_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdate',
            name='last_changed_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupdateseries',
            name='last_changed_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
