# Generated by Django 2.1.2 on 2018-12-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0007_auto_20181208_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupdateseries',
            name='pickups_created_until',
        ),
    ]
