# Generated by Django 2.1.5 on 2019-01-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0008_auto_20190105_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupdatecollector',
            options={'ordering': ['created_at']},
        ),
    ]
