# Generated by Django 2.1.2 on 2018-12-10 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0008_remove_pickupdateseries_pickups_created_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupdate',
            old_name='is_cancelled',
            new_name='is_disabled',
        ),
        migrations.AlterField(
            model_name='pickupdate',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_changed', to=settings.AUTH_USER_MODEL),
        ),
    ]
