# Generated by Django 2.1.2 on 2018-10-22 15:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0022_fix_wrong_latest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0002_auto_20180226_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.ConversationMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
