variables:
  build_settings: &build_settings
    platforms: linux/amd64
    repo: codeberg.org/${CI_REPO}
    registry: codeberg.org
    auto_tag: false
    username: ${CI_REPO_OWNER}
    password:
      from_secret: cb_token
    logins:
      - registry: docker.io
        username: nicksellen
        password:
          from_secret: docker_token

steps:
  - name: "build latest image"
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      <<: *build_settings
      build_args:
        - KARROT_VERSION=latest
        - KARROT_COMMIT=${CI_COMMIT_SHA}
      tags: latest
      cache_images:
        - codeberg.org/${CI_REPO}-cache:main
    when:
      - event: push
        branch: main

  - name: "build tag image"
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      <<: *build_settings
      build_args:
        - KARROT_VERSION=${CI_COMMIT_TAG}
        - KARROT_COMMIT=${CI_COMMIT_SHA}
      tags: ${CI_COMMIT_TAG}
      cache_from: codeberg.org/${CI_REPO}-cache:main
    when:
      - event: tag