# this is for building the "latest" image from main branch

when:
  - event: push
    branch: main

depends_on:
  - test

steps:
  - name: "build latest image"
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: false
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      logins:
        - registry: docker.io
          username: nicksellen
          password:
            from_secret: docker_token
      build_args:
        - KARROT_VERSION=latest
        - KARROT_COMMIT=${CI_COMMIT_SHA}
      tags: latest
      cache_images:
        - codeberg.org/${CI_REPO}-cache:main
