steps:
  - name: "Build docker image"
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      - event: push
        branch: main
      - event: tag
      - event: manual

depends_on:
  - test
