when:
  - event: manual
  - event: push
    branch: main

skip_clone: true

steps:
  - name: "deploy"
    image: codeberg.org/karrot/plugin-deploy-karrot
    pull: true
    settings:
      ssh_key:
        from_secret: ssh_key_karrot_dev_deploy
