when:
  - event: manual
  - event: push
    branch: main

depends_on:
  - build-latest

skip_clone: true

steps:
  - name: "deploy"
    image: codeberg.org/karrot/plugin-karrot-deploy
    pull: true
    settings:
      ssh_key:
        from_secret: ssh_key_karrot_dev_deploy
