when:
  # anything on or targeting the main branch
  # pull requests must be labelled with ci/test
  - evaluate: 'CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH && (CI_PIPELINE_EVENT == "push" || (CI_PIPELINE_EVENT == "pull_request" && CI_COMMIT_PULL_REQUEST_LABELS contains "ci/test"))'
  - event: manual

steps:

  # The tests are run inside a docker image that we build
  # from the main Dockerfile, so it closely resembles
  # the production environment

  - name: "build test image"
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}-test
      registry: codeberg.org
      auto_tag: false
      tags: tmp-${CI_COMMIT_SHA:0:8}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      logins:
        - registry: docker.io
          username: nicksellen
          password:
            from_secret: docker_token

  - name: "test"
    image: codeberg.org/${CI_REPO}-test:tmp-${CI_COMMIT_SHA:0:8}
    environment:
      - MODE=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=karrot
      - DATABASE_USER=karrot
      - DATABASE_PASSWORD=karrot
      - REDIS_HOST=redis
      - SECRET_KEY=notverysecret
    directory: /app/code
    commands:
      - mkdir -p test-reports
      - pytest -n auto --cov=karrot --cov-report xml --junitxml=test-reports/junit.xml

services:
  - name: database
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_DB=karrot
      - POSTGRES_USER=karrot
      - POSTGRES_PASSWORD=karrot
  - name: redis
    image: "redis:6-alpine"
