services:
  - name: database
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=karrot
      - POSTGRES_DB=karrot
      - POSTGRES_PASSWORD=karrot
  - name: redis
    image: "redis:6-alpine"

steps:
  - name: "Test"
    image: "codeberg.org/karrot/ci:latest"
    pull: true
    environment:
      - MODE=dev
      - DATABASE_HOST=database
      - DATABASE_NAME=karrot
      - DATABASE_USER=karrot
      - DATABASE_PASSWORD=karrot
      - REDIS_HOST=redis
      - SECRET_KEY=notverysecret
    commands:
      - ./sync.py
      - mkdir -p test-reports
      - pytest -n $(nproc) --cov=karrot --cov-report xml --junitxml=test-reports/junit.xml
    when:
      - branch: master
      - event: tag
