# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20170212_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupdate',
            options={'default_permissions': [], 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='pickupdateseries',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': []},
        ),
    ]
