# Generated by Django 2.1.1 on 2018-09-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_remove_activity_notifications_sent'),
    ]

    operations = [
        # add explicit through model for activity participants
        # nothing in the database should change, we only need to make sure that Django accepts the state change
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ActivityParticipant',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                    ],
                    options={
                        'db_table': 'activities_activity_participants',
                    },
                ),
                migrations.AlterField(
                    model_name='activity',
                    name='participants',
                    field=models.ManyToManyField(
                        related_name='activities',
                        through='activities.ActivityParticipant',
                        to=settings.AUTH_USER_MODEL
                    ),
                ),
                migrations.AddField(
                    model_name='activityparticipant',
                    name='activity',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
                ),
                migrations.AddField(
                    model_name='activityparticipant',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterUniqueTogether(
                    name='activityparticipant',
                    unique_together={('activity', 'user')},
                ),
            ],
        ),
    ]
