# Generated by Django 2.1.5 on 2019-01-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20181216_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityparticipant',
            options={'ordering': ['-created_at']},
        ),
    ]
