# Generated by Django 2.1.5 on 2019-01-13 15:52

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20190106_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
        ),
    ]
