# Generated by Django 2.1.5 on 2019-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20190122_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_duration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
