# Generated by Django 3.0.7 on 2020-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20191015_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipant',
            name='reminder_task_id',
            field=models.TextField(null=True),
        ),
    ]
