# Generated by Django 3.0.7 on 2020-07-03 11:38

from django.db import migrations, models
from django.db.models import F, Avg


def recalculate_weight(apps, schema_editor):
    Feedback = apps.get_model('activities', 'Feedback')
    Activity = apps.get_model('activities', 'Activity')

    # copy the old values from "weight" field to "weight_for_average" field
    Feedback.objects.filter(about__feedback_as_sum=False).update(weight_for_average=F('weight'))

    for activity in Activity.objects.filter(feedback_as_sum=False):
        feedback_with_weight = activity.feedback_set.exclude(weight=None)
        feedback_with_weight_count = feedback_with_weight.count()

        if feedback_with_weight_count > 0:

            # the average value is what we consider the total weight of the pickup
            average = feedback_with_weight.aggregate(value=Avg('weight'))['value']

            # so now the weights are summed
            # we just pretend that each person just picked up an equal share of the weight
            weight_per_participant = average / feedback_with_weight_count
            feedback_with_weight.update(weight=weight_per_participant)

    Activity.objects.filter(feedback_as_sum=False).update(feedback_as_sum=True)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_feedback_weight_for_average'),
    ]

    operations = [
        migrations.RunPython(recalculate_weight, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
