# Generated by Django 3.0.9 on 2020-08-16 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0042_auto_20200507_1258'),
        ('activities', '0021_remove_activity_feedback_as_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='groups.Group')),
                ('name', models.CharField(max_length=80)),
                ('colour', models.CharField(max_length=6)),
                ('icon', models.CharField(max_length=32)),
                ('feedback_icon', models.CharField(max_length=32)),
                ('has_feedback', models.BooleanField(default=True)),
                ('has_feedback_weight', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.ActivityType'),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_series', to='activities.ActivityType'),
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('group', 'name')},
        ),
    ]
