# Generated by Django 3.1.3 on 2020-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_add_task_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=100),
        ),
    ]
