# Generated by Django 3.1.3 on 2020-11-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_add_activity_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
