# Generated by Django 3.1.4 on 2021-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_add_activity_type_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_trial_participants',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
