# Generated by Django 3.1.6 on 2021-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_add_activity_type_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipant',
            name='feedback_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
