# Generated by Django 3.1.4 on 2021-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_activityparticipant_feedback_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants_without_role',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='is_without_role',
            field=models.BooleanField(default=False),
        ),
    ]
