# Generated by Django 3.1.4 on 2021-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_add_activity_require_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('max_participants_without_role', None), models.Q(_negated=True, require_role=''), _connector='OR'), name='only_trial_participants_if_require_role'),
        ),
    ]
