# Generated by Django 3.2.5 on 2021-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_activityparticipant_feedback_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='feedback_icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
