# Generated by Django 3.1.4 on 2021-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_add_trial_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='require_approval',
        ),
        migrations.AddField(
            model_name='activity',
            name='require_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
