# Generated by Django 3.2.10 on 2022-02-14 13:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20210714_2116'),
    ]

    operations = [
        # need to have btree_gist extension
        # could create it here, but then would have to run migations as superuser
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['date'], name='activities__date_5ffa2e_gist'),
        ),
    ]
