# Generated by Django 3.2.10 on 2022-02-14 13:11

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20210714_2116'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['date'], name='activities__date_5ffa2e_gist'),
        ),
    ]
