# Generated by Django 3.2.5 on 2021-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_auto_20210116_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityseries',
            name='max_open_participants',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='require_role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
