# Generated by Django 3.2.9 on 2021-12-20 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_backfill_participant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='max_participants',
        ),
    ]
