# Generated by Django 3.2.5 on 2021-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_auto_20210714_1301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activityseries',
            constraint=models.CheckConstraint(check=models.Q(('max_open_participants', None), models.Q(('require_role', None), _negated=True), _connector='OR'), name='series_only_open_participants_if_require_role'),
        ),
    ]
