# Generated by Django 3.2.5 on 2021-07-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20210714_2116'),
        ('activities', '0033_activityseries_series_only_open_participants_if_require_role'),
    ]

    operations = [
    ]
