# Generated by Django 3.2.9 on 2021-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_remove_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
