# Generated by Django 3.2.9 on 2021-12-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_activity_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='participant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.participanttype'),
        ),
    ]
