# Generated by Django 3.2.7 on 2021-11-23 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_merge_20210715_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=100, null=True)),
                ('max_participants', models.PositiveIntegerField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_roles', to='activities.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='participant_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.participantrole'),
        ),
    ]
