# Generated by Django 3.2.15 on 2022-08-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_backfill_participant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='max_participants',
        ),
    ]
