# Generated by Django 3.2.15 on 2022-08-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0035_remove_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='participant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.participanttype'),
        ),
    ]
