# Generated by Django 3.2.15 on 2022-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_alter_activityparticipant_participant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
