# Generated by Django 3.2.15 on 2022-08-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_icsauthtoken'),
        ('activities', '0036_auto_20211228_2046'),
    ]

    operations = [
    ]
