# Generated by Django 3.2.7 on 2021-11-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_backfill_participant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='participant_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.participantrole'),
        ),
    ]
