# Generated by Django 3.2.15 on 2022-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='public_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
