# Generated by Django 3.2.7 on 2021-11-23 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_participantrole_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesParticipantRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=100, null=True)),
                ('max_participants', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('activity_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_roles', to='activities.activityseries')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
