# Generated by Django 3.2.15 on 2022-09-19 10:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='banner_image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='activity__banner_images', verbose_name='BannerImage'),
        ),
    ]
