# Generated by Django 3.2.7 on 2021-11-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_seriesparticipantrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantrole',
            unique_together={('activity', 'role')},
        ),
    ]
