# Generated by Django 3.2.15 on 2022-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_activity_public_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('is_public', False), ('public_id__isnull', False), _connector='OR'), name='public_activities_must_have_public_id'),
        ),
    ]
