# Generated by Django 3.2.15 on 2022-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_auto_20220919_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='public_id',
            field=models.UUIDField(null=True),
        ),
    ]
