# Generated by Django 3.2.15 on 2022-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_activity_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='public_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
