# Generated by Django 3.2.7 on 2021-11-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_alter_participantrole_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesparticipantrole',
            unique_together={('activity_series', 'role')},
        ),
    ]
