# Generated by Django 3.2.9 on 2021-11-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0041_alter_seriesparticipantrole_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityseries',
            name='series_only_open_participants_if_require_role',
        ),
    ]
