# Generated by Django 3.2.9 on 2021-11-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0042_remove_activityseries_series_only_open_participants_if_require_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activity',
            name='only_open_participants_if_require_role',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_open_participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_role',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='max_open_participants',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='require_role',
        ),
    ]
