# Generated by Django 4.2.7 on 2023-12-18 18:42

from django.db import migrations, models
from django.utils import timezone


def set_activity_has_started(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    now = timezone.now()
    # Update all existing ones to have started
    # (saves processing them the first time process_activities() runs)
    Activity.objects.filter(has_started=False, date__startswith__lt=now).update(has_started=True)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0042_activity_has_started'),
    ]

    operations = [
        migrations.RunPython(set_activity_has_started, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
