# Generated by Django 3.2.9 on 2021-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0043_auto_20211129_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='max_participants',
        ),
    ]
