# Generated by Django 3.2.9 on 2021-12-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0044_auto_20211129_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrole',
            name='series_participant_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_roles', to='activities.seriesparticipantrole'),
        ),
    ]
