# Generated by Django 3.2.9 on 2021-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0045_participantrole_series_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrole',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seriesparticipantrole',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
