# Generated by Django 3.2.9 on 2021-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0046_auto_20211213_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantrole',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seriesparticipantrole',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
