# Generated by Django 4.2.7 on 2024-01-12 15:44

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0047_activitytype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityseries',
            name='banner_image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='activity_series__banner_images', verbose_name='BannerImage'),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
