# Generated by Django 2.1.4 on 2018-12-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_place_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='created_by',
            new_name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='place',
            name='deleted',
        ),
    ]
